# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:

  routing_loader :
    default_format: json
    include_format: false
  format_listener:
    rules:
      - { path: '^/orders', priorities: ['json'], fallback_format: json }
      - { path: '^/api', priorities: ['json'], fallback_format: json }
      - { path: '^/test', priorities: ['json', 'html'], fallback_format: json }
      - { path: '^/coordinate', priorities: ['json'], fallback_format: json }
      - { path: '^/csv', priorities: ['json'], fallback_format: json }
      - { path: '^/jsonl', priorities: ['json'], fallback_format: json }
      - { path: '^/sendmail', priorities: ['json'], fallback_format: json }

  exception:
    enabled: true

  view:
    view_response_listener: 'force'
    formats:
      json: true

